name: Build Plugin
on:
  release:
    types: [ published ]
jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Build Project
        run: |
          composer run release
          mkdir build
      - name: Create Artifact
        uses: montudor/action-zip@v0.1.0
        with:
          args: zip -X -r build/bm-wp-experience.zip . -x *.git*  node_modules** .* "*/\.*" *.dist assets/styles/src** composer.* build** config** CHANGELOG.md README.md webpack.mix.js package.json package-lock.json phpstan.neon mix-manifest.json
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: bm-wp-experience
          path: build/bm-wp-experience.zip
      - name: Add to Release
        uses: JasonEtco/upload-to-release@master
        with:
          args: build/bm-wp-experience.zip application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
